---
- name: Ansible roles names without prefix 
  set_fact:
    ansible_role_names_cleaned: "{{ ansible_role_names|
                 map('regex_replace', regex, replace)|
                 list }}"
  vars:
    regex: '^(.*)\.(.*)$'
    replace: '\2'

- name: lcm_roles_node
  set_fact: lcm_roles_node="{{ lcm_roles | intersect(ansible_role_names_cleaned) }}"

#- name: Product role version homes 
#  set_fact:
#    "{{ item }}_home_version": "{{ vars[item + '_home'] }}/{{ vars[item + '_home'] | basename }}-{{ vars[item + '_version'] }}"
#  with_items: '{{ lcm_roles_node }}'

#- name: Product role version database names 
#  set_fact:
#    "{{ item }}_database_name_version": "{{ vars[item + '_database_name'] }}_{{ vars[item + '_version']|replace('.','_') }}"
#  with_items: '{{ lcm_roles_node }}'

- name: LCM info 
  lcm_info:
    role: '{{ item }}'
    version: "{{ vars[item + '_version'] }}"
    home: "{{ vars[item + '_home'] }}"
    database: "{{ vars[item + '_database_name'] | default(omit) }}"
    versions_sequence: "{{ vars[item + '_versions_sequence'] }}"
  with_items: '{{ lcm_roles_node }}'

- name: LCM info
  debug:
    var: "{{ item }}_lcm" 
  with_items: '{{ lcm_roles_node }}'

- name: Database version
  debug:
    var: "{{ item }}_database_name_version" 
  with_items: '{{ lcm_roles_node }}'

- name: Home version
  debug:
    var: "{{ item }}_home_version" 
  with_items: '{{ lcm_roles_node }}'

- name: Home link
  debug:
    var: "{{ item }}_home_link" 
  with_items: '{{ lcm_roles_node }}'

- name: Home link home
  debug:
    var: "{{ item }}_home_link_home" 
  with_items: '{{ lcm_roles_node }}'

- name: Home link app
  debug:
    var: "{{ item }}_home_link_app" 
  with_items: '{{ lcm_roles_node }}'
