---
backup_mount: /backup
backup_logs: /backup/logs
backup_tmp: /backup/tmp
backup_archives: /backup/archives
backup_split_into_chunks_of: 1000000
backup_alias_prefix: tpelcm
backup_cron_jobs: true
backup_restore_db: false
backup_restore_home: false

backup_roles_supported: ['sonarqube', 'nexus', 'bitbucket', 'myapp']

backup_roles:
  sonarqube:
    stop_start_service: sonarqube
    keep: { daily: 3, weekly: 2, monthly: 0, manual: 1 }
  nexus:
    stop_start_service: nexus
    keep: { daily: 1, weekly: 0, monthly: 0, manual: 1 }
    tar_options: -h
  bitbucket:
    stop_start_service: bitbucket
    keep: { daily: 3, weekly: 2, monthly: 0, manual: 1 }
  myapp:
    # stop_start_service: myapp
    keep: { daily: 1, weekly: 0, monthly: 0, manual: 1 }
    # snapshot: true
    # schedules: ['daily', 'weekly', 'monthly', 'manual']

backup:
  schedules_default: ['daily', 'weekly', 'monthly', 'manual']
  schedules:
    daily: 50 2 * * 1,2,3,4,5
    weekly: 50 2 * * 6
    monthly: 50 2 1 * *

backup_restored: []

backup_notify_mail:
  enabled: false
  from: backup@mydomain.com
  to: admin@mydomain.com
  address: mail.local
  port: 25
  domain: mydomain.local
  on_success: 'true'
  on_warning: 'true'
  on_failure: 'true'
  #encryption: ':none'

backup_notify_slack:
  enabled: false 
  webhook: https://hooks.slack.com/services/...
  channel: infra
  on_success: 'true'
  on_warning: 'true'
  on_failure: 'true'

backup_utility:
  ubuntu:
    v18:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-ubuntu1804/backup_5.0.0.beta.2-1_amd64.deb
      checksum: 2363ac2e8d5f38bafd2401d4fec84c9eef548f612f30a76cb82a2fe2d4dc0ec8
  redhat:
    v7:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-el7/backup-5.0.0.beta.2-1.el7.x86_64.rpm
      checksum: ce4170985fbce068a9b16d08e916ac570af0a82dcdb9c2286753f800bbb90d77
  centos:
    v7:
      url: https://github.com/tpelcm/omnibus-backup/releases/download/v5.0.0.beta2-1-el7/backup-5.0.0.beta.2-1.el7.x86_64.rpm
      checksum: ce4170985fbce068a9b16d08e916ac570af0a82dcdb9c2286753f800bbb90d77

#backup_restore:
#   sonarqube: 
#     folder: 2019.10.03.05.21.29
#     folder: '*'
#     path: 
#     force: true

