---
- name: Generate private key
  openssl_privatekey:
    path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}reverse_proxy.pem"

- name: Generate CSR
  openssl_csr:
    path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.csr"
    privatekey_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}reverse_proxy.pem"
    common_name: "{{ reverse_proxy_vhosts[item].server_name }}"
  with_items: "{{ reverse_proxy_vhosts }}"

- name: Generate certificate.
  openssl_certificate:
    path: "{{ reverse_proxy_etc_ssl_certs[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.pem"
    privatekey_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}reverse_proxy.pem"
    csr_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.csr"
    provider: selfsigned
  with_items: "{{ reverse_proxy_vhosts }}"