---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-squid
      squid_port: 3128
      squid_cache_dir: aufs /var/spool/squid 16000 16 256 max-size=8589934592
      squid_cache_replacement_policy: heap LFUDA
      squid_maximum_object_size_mb: 256
      squid_acls:
        - name: repmod
          classifier: url_regex
          value: '/repomd\.xml$'
      squid_cache_rules:
        - acl: repmod
          decision: deny
