---
- name: bitbucket.yml
  hosts: bitbucket
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: postgresql-client,            tags: ["bitbucket", "postgresql"] }    
    - { role: java,                         tags: ["bitbucket", "java"] }
    - { role: geerlingguy.git,              tags: ["bitbucket"] }
    - { role: bitbucket,                    tags: ["bitbucket"] }
    - { role: backup,                       tags: ["common", "backup"] }

  vars:
    git_install_from_source: true
    git_version: "2.16.2"
    git_install_from_source_force_update: true
