---
- name: chown-site-owner
  file: 
    path: "/var/www/html/{{ sites[item]['context'] }}"
    owner: "{{ sites[item]['owner'] }}"
    group: "{{ sites[item]['owner'] }}"    
    state: directory
    recurse: yes 
  with_items: "{{ sites }}"
  when: sites[item]['owner'] is defined    