---
sites_server_admin: admin@tpelcm.tech
sites_server_name: sites

sites_log_level: warn # debug, info, notice, warn, error, crit,
sites_certs: generate # or download

sites_port: 8080

apache_create_vhosts: no
apache_remove_default_vhost: true

sites_etc_ssl_private:
  Debian: /etc/ssl/private/
  RedHat: /etc/ssl/

sites_etc_ssl_certs:
  Debian: /etc/ssl/certs/
  RedHat: /etc/ssl/

https_log_dir:
  Debian: /var/log/apache2/
  RedHat: /var/log/httpd/

sites:
  example:
    url: https://github.com/cloudacademy/static-website-example.git
    context: dimension
  example2:
    context: dimension-with-key
    owner: dimension
    authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfk2GlYqNKRedzENzvc0rgAnwDxJKm6thoHvVvKvf81HkOSwx6PPpmy/Y5rM2lJgVdEcdd5JGaZZ0TqlV7N1jywmHyRkE02W2v8GjTt2KExvapBFgjeyQEZl9V1EERBBQURsW/fv/urMz9sKvLUas7CUs/+STuVze0c9TgK7ooSRkvm9+Kbh03X2SEAC+cFLEDZtv0iiCaN+0l7epoINhJFiu7FloMeN+4s1M4m2vHupSKdkb4Mg4hTp+7mbWHSN7Gk0kLsKPfilMPGofe3gVv6Es5JK2jeM8/PqvmtQsVRIUqh2PsJb4Eb4RWFZGWVFZqdngtlDaDZ+Ssv2zZtRijywKCfYl6Q/ZbhIIlx70JYDVEoQGDXBH8wBpJboErOEwV//mNg3rtEMlIrGnMFUTKXogMAsc/zjuFjbjII034/RPA8WlT5/4emYHaKMH2cKTVuIslBRFUC0Oq//dUnVmNwNBMZMWU1TpXr0ZuTirZleRuIliFYx6e93j+bOaPQr8oKLRntH8tasMILdlYwdHjZnZofhuyLWa2YFilhLxRTY9Ne2WiZUwf0mE+ExLW5yBo3fLEs7dLX9po/jbUU6lM/ROrDC1XaPs53V99zB+yPr5yOykvnZAAzPh6IfpYG9dcIQD2VPvtKaJzHDl4WVy5mzmuZpuikcgbaGVQHEXhlQ== sites

sites_ssh:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEA35NhpWKjSkXncxDc73NK4AJ8A8SSpurYaB71byr3/NR5DksM
    ejz6Zsv2OazNpSYFXRHHXeSRmmWdE6pVezdY8sJh8kZBNNltr/Bo07dihMb2qQRY
    I3skBGZfVdRBEQQUFEbFv37/7qzM/bCry1GrOwlLP/kk7lc3tHPU4Cu6KEkZL5vf
    im4dN19khAAvnBSxA2bb9IogmjftJe3qaCDYSRYruxZaDHjfuLNTOJtrx7qUinZG
    +DIOIU6fu5m1h0jexpNJC7Cj34pTDxqH3t4Fb+hLOSSto3jPPz6r5rULFUSFKodj
    7CW+BG+EVhWRllRWanZ4LZQ2g2fkrL9s2bUYo8sCgn2JekP2W4SCJce9CWA1RKEB
    g1wR/MAaSW6BKzhMFf/5jYN67RDJSKxpzBVEyl6IDALHP847hY24yCNN+P0TwPFp
    U+f+HpmB2ijB9nCk1biLJQURVAtDqv/3VJ1ZjcDQTGTFlNU6V69Gbk4q2ZXkbiJY
    hWMenvd4/mzmj0K/KCi0Z7R/LWrDCC3ZWMHR42Z2aH4bsi1mtmBYpYS8UU2PTXtl
    omVMH9JhPhMS1ucgaN3yxLO3S1/aaP421FOpTP0TqwwtV2j7Od1ffcwfsj6+cjsp
    L52QAMz4eiH6WBvXXCEA9lT77Smicxw5eFlcuZs5rmabopHIG2hlUBxF4ZUCAwEA
    AQKCAgB87/A+KovTgpLfQ0ojaUsrOVgyBtRpAI2kScCfueRQ3i8z5I55dL/9V/cl
    rcJRipiutLOzbXpMTIJlrecM7xX+us9fQxFHRkW8bt01iqI8Tq8iLjJOyY6MAuU9
    olol9yB9YDs7Uu4UY24+Sk8GVIIagIwTmNehdQ3FAoGwL99cidTQPQvDYNtkySLz
    fOMeFpYAr6c01Ud4xs34RyaZv9j9pq0TZF833wguP8++r2Ogfkxpv8TTB63LwRMU
    E8ZUbk1HrKDCLpi036igpRPOYEWrjqUSrsN1uZoe3pfTWdJytRKxfG1DVqgD9ImA
    TZdI6aJM5h0sY0m/TvyD6Ikcc83rFh6lssx4mF9+6aFBjfH3IDVI8K1MomuTgYnn
    jWIdfrooGXmV7hIR/FtNG2noLD/F4HnOaySO7kGAPbpqKxPdeG+yj0GFqtpE64Zj
    HhHj8ULh43McypWBuYiN7KrNEuj797CcHrVUNcpaEotmKBDtptOCvdzG/Ol5kV4E
    y62SZq1Yl1C51TN4WJB1OJkgfA6xxSr/6REbsMnheLucbH7GfVM0F4RkHipsF477
    3f3vOQ8WqmBMoeiY7tsG863bpaGl6QU3+SCdDf69gMBlDLTVx2L5FspZEPWzjWWD
    BLpEGCzpiAx3k65SmnDKIeALiFY6vDQlalcj9ayHp9EoKHV6FQKCAQEA/3KJ+9bF
    R6rfef+tDu/kftjDVKl9/y1QNZlZYFba+kBEYKecTP0bPynUufLYA32dfN3BO4Oz
    Ad7U6kHgzRlrUQxIiCfr4tCPgH2vn/aAHeGn2Pbm3jFEccMDrsEdUNDKIpBA0Ca6
    KZHIMd3q9pdivxpN9nIKNPdE4rkDRqQAH8jRmG0YYnqZVdYbVVyFiEjywZSFrcsQ
    KmmZ/4HSTfbYfQr7zP0Lg0C3CH4Wb8g/Zs5GCls1ciBYPcfIQ6GmiJAuaeAIR0zn
    k4SPJZ8jA/WeWbiN//sboji1fCHiN248QagBh3jwHNCjLIMzewKsrnj/ghAhhwmq
    dP1nHShvOOif3wKCAQEA4A8xTi/AOg1Y322gLD81bogJ5JLQF8tSPdcDgcN7eHOE
    0TX/81K9LIjfG6aGMoGZ/vL58dkVJjltoSHVl6H+hpa7vZO3Pm9GX6ulPjzkIyry
    YooVnHRQDjGs/d7HMzctERZSiQcZR8lNpLl5mDaaJd/5Dxx88ahkv8YN6cH7XPty
    MOVVwHeOM+oGmNGmX+xsyHFdeCQkbXAG6EI031u2D7sa2kEckpOsYij59Rr6/fPX
    R+Mk2c4uEiDnLz4X6SkhS+a+idkMCASHQNtUukv2aJ07VkVOqzxPBRXr1Mj1kG6T
    Jnd0Cl7RgFaZeCqr/Exll2e1lJxq18176n0Rsi1dCwKCAQEApp8Tmg2RSRoQAwfe
    3itkI8lIP+T+pn/sHcoVHl4JH8rjzxgFP8KpDx49/7yDYmOBYn1TGXriPIoY32Rx
    OdcmxQr6FLXVi3D26Z0R/YlQMC2MylziYnRIbNwDfu3ALYLDFqB5ZkyciZjpuH1E
    UeyVIIoL6ICiX8IaULjVhjJbUmAvNvmSOko10mOCGL/s6eSLU/GI8L/Pn5qaNKt9
    fhVRSN7tN9ymscp4mTWFdQxtLqXF0eOEjRjD9ihmXJcIhXNmkvDq9XcYZoTEyolu
    0ZpY27UiCqLEd5/94SZI5FcnPrxTowYjuOfuR46c+dPYx0VthGz5MZgAc6cGp2JE
    ih5SiQKCAQAbSf5pVWuGJoYCgGmXugMZ+TurOS5bF4pmub9VmKd7Hia5DGimDBe6
    StlRltCVai+FW7aRfC0VQL1XeLV5CGPlpIotJsaUthzOHiu8DtKCbgKjecn0Cj6N
    3AMD0JRWaov0ntFimxi7I4tvWp+yqEPSBRtiecfF7wqGSOr844Fn68AWsHfnPyh0
    rjYreq1W1YbSSuxla5F8Or68nwOtiI/+Dn3Qw0llmNLQCcmXzrdvIrm/qaydUn1N
    ++/sUxW6ciX6BpqCU4shltuaTJxfLE1QpIXLlhlkxa2iIu9cNTWjZ7RIZRgfAzlk
    9icu+ZOE4REmhZ0aAosIyaAkCSOUne3NAoIBAGlbUbSaqm5KNuCPfB/XmGr3IPId
    ui+8/oSQU6EiApsmGFm1jfZABDgE0JOyRCirT6O402Q+V2V7y7g5SspM3ApViWbF
    zQ8AMlpq+2UtJxqgRoTW8t+qSdyGwc9s/kDBr7SKQV1JhKWSY+2ztT3KoDJ6Sjcn
    Dsv1oEzmBeDbP6VRM39gkOl7MkXikhV7EiW29lLvL2cILfHR1kce6JN/GFF6B3rp
    mln1Kd1MKvITUOvzrvAdSyRv8LjG2xddhhi0zIWA8OrTRr2VlkT0CMp1hjYHJdM3
    XiS7BpOfKrTQiGCpk0tvPX3h10FfPGfq2eMymUer39w+74+vFc9febYUW+w=
    -----END RSA PRIVATE KEY-----
  pub_key: > 
    ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfk2GlYqNKRedzENzvc0rgAnwDxJKm6thoHvVvKvf81HkOSwx6PPpmy/Y5rM2lJgVdEcdd5JGaZZ0TqlV7N1jywmHyRkE02W2v8GjTt2KExvapBFgjeyQEZl9V1EERBBQURsW/fv/urMz9sKvLUas7CUs/+STuVze0c9TgK7ooSRkvm9+Kbh03X2SEAC+cFLEDZtv0iiCaN+0l7epoINhJFiu7FloMeN+4s1M4m2vHupSKdkb4Mg4hTp+7mbWHSN7Gk0kLsKPfilMPGofe3gVv6Es5JK2jeM8/PqvmtQsVRIUqh2PsJb4Eb4RWFZGWVFZqdngtlDaDZ+Ssv2zZtRijywKCfYl6Q/ZbhIIlx70JYDVEoQGDXBH8wBpJboErOEwV//mNg3rtEMlIrGnMFUTKXogMAsc/zjuFjbjII034/RPA8WlT5/4emYHaKMH2cKTVuIslBRFUC0Oq//dUnVmNwNBMZMWU1TpXr0ZuTirZleRuIliFYx6e93j+bOaPQr8oKLRntH8tasMILdlYwdHjZnZofhuyLWa2YFilhLxRTY9Ne2WiZUwf0mE+ExLW5yBo3fLEs7dLX9po/jbUU6lM/ROrDC1XaPs53V99zB+yPr5yOykvnZAAzPh6IfpYG9dcIQD2VPvtKaJzHDl4WVy5mzmuZpuikcgbaGVQHEXhlQ== sites
